// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDeyE-Mrfv0JGQFKQ8BC5c1sYYwiduAqyU',
    appId: '1:316051278674:web:ee272a2108e102dc18488b',
    messagingSenderId: '316051278674',
    projectId: 'flutterchatapp-a27ef',
    authDomain: 'flutterchatapp-a27ef.firebaseapp.com',
    storageBucket: 'flutterchatapp-a27ef.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYr8tgCHkcwHuVNv8nN9mx6C-350rkuXI',
    appId: '1:316051278674:android:a602a3ba92bb021618488b',
    messagingSenderId: '316051278674',
    projectId: 'flutterchatapp-a27ef',
    storageBucket: 'flutterchatapp-a27ef.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB69UIXch3JNIE6KJlH1bepIrRKMXM9bEQ',
    appId: '1:316051278674:ios:b57560025bcc590418488b',
    messagingSenderId: '316051278674',
    projectId: 'flutterchatapp-a27ef',
    storageBucket: 'flutterchatapp-a27ef.appspot.com',
    androidClientId: '316051278674-bm5pgpvddpkrsrmvdrn95c53e0ln44o2.apps.googleusercontent.com',
    iosClientId: '316051278674-ee6gd8ga8bna501sdkhr3utq07i18444.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB69UIXch3JNIE6KJlH1bepIrRKMXM9bEQ',
    appId: '1:316051278674:ios:e9f48146ad4212b518488b',
    messagingSenderId: '316051278674',
    projectId: 'flutterchatapp-a27ef',
    storageBucket: 'flutterchatapp-a27ef.appspot.com',
    androidClientId: '316051278674-bm5pgpvddpkrsrmvdrn95c53e0ln44o2.apps.googleusercontent.com',
    iosClientId: '316051278674-5nq7m9s7v4ohk472kriqagm3nel96oo1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterChatapp.RunnerTests',
  );
}
